######################################################################
# Automatically generated by qmake (3.0) Mon May 11 22:02:56 2015
######################################################################

QT += widgets

SOURCES = main.cpp

#install 
target.path = ./
INSTALLS += target
